name: continuous-integration

on: [ push ]

jobs: 
  
  # test-python:
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [ ubuntu-latest, macos-latest, windows-latest ]
  #       python-version: [ "3.8", "3.9", "3.10", "3.11" ]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Display Python version
  #       run: |
  #         which python
  #         python --version
  #     - name: Build package and create dev environment
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -e .[dev]
  #     - name: Show PIP list
  #       run: |
  #         pip list
  #     - name: Run test
  #       run: |
  #         pytest
  
  run-documentation:
    runs-on: ubuntu-latest
    needs: test-python
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs "mkdocstrings[python]" mkdocs-material
      - name: Show pip list
        run: |
          pip list